app = 'laptop-remote-relay'
primary_region = 'sin'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[processes]
  app = 'python3 persistent_cloud_relay.py'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
